### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by iusmanalimughal** [ReaperAnon/SekiroHotkeySystem#3]
Hello, i watched your video on YouTube and i came here
I followed the steps but i can't see any button on top and can't open it via Tab button. 
Disput. file was not overwrite so i copied in in sekiro folder where   sekiro.exe file was exist. 
Help me so i can use it.

**Comment by ReaperAnon** [comment]
All of the files go near sekiro.exe not just that one.

**Comment by iusmanalimughal** [comment]
> All of the files go near sekiro.exe not just that one. 

I paste all the files anf folders but didn't work
Please upload a complete video on your YouTube channel.
